### ISSUE TITLE
Add option to disable display in CLI

### ISSUE THREAD

**Issue by vandalt** [SAIL-Labs/AMICAL#124]
I think it would be nice to be able to disable displaying the figures when processing multiple files via CLI. Maybe adding a `--display` (or `--no-display`) flag as well as an option to save figures? If both showing and saving are off, then figure creation can be skipped completely.

**Comment by DrSoulain** [comment]
Yes indeed, I thought it was already the case. I will check that soon, thanks.

**Comment by DrSoulain** [comment]
Hi @vandalt, by default figures plot are skipped during clean, extract or calibrate step. You need to specify -p (--plot) to show the figures.

**Comment by vandalt** [comment]
You're right, sorry I missed that part. Do you think it would be worth also setting the `display` argument of amical functions to `False` as well when none of `--plot` or `--save-to` are used ?

**Comment by DrSoulain** [comment]
Do you propose to turn the display arguments to false by default everywhere?

**Comment by vandalt** [comment]
Not by default in AMICAL necessarily, but in the CLI calls. For example, in the block below, set `display=False` in the first clause because the figures are not used, and set to `True` only if `--plot` is used (in other steps, this would also require looking for `--save-to` to see if the figures are saved, if I understand correctly).

**Comment by neutrinoceros** [comment]
FWIW this sounds good to me
