### ISSUE TITLE
TST: CI instability (setuptools + munch)

### ISSUE THREAD

**Issue by neutrinoceros** [SAIL-Labs/AMICAL#161]
CI is currently unstable because (see https://github.com/SAIL-Labs/AMICAL/actions/runs/4180212707)
What happens is that the newest version of `setuptools` (namely `67.3`), which provides `pkg_resources`, deprecates `pkg_resources.declare_namespece` (see https://github.com/pypa/setuptools/pull/3434), which is used by `munch`.

This has been a problem with munch for a while already (see https://github.com/Infinidat/munch/issues/67), and [it's actually been solved on the dev branch for 3 years](https://github.com/Infinidat/munch/pull/64), but the patch was never released, and now the repo looks essentially unmaintained.

I would advocate that we should try to get rid of `munch` as a dependency, though I may not be fully aware of what challenges this poses. TBD with @DrSoulain

**Comment by DrSoulain** [comment]
Indeed, `munch` seems to be too unstable to be used. It is only used to transform dictionary into class-like object to be easily accessible. We should be able to write a built-in dedicated function to do so.

**Comment by vandalt** [comment]
In the past, I used Box for a similar purpose. It seems still well maintained: https://github.com/cdgriffith/Box.

**Comment by vandalt** [comment]
Oops I just realized this had been closed already. Will leave the comment in case it can help someone in the future.

**Comment by neutrinoceros** [comment]
Good to know ! If we ever want to stop vendoring munch, this seems like a decent option
